"""changes on the validation ruleset model

Revision ID: 6551336d8f9a
Revises: fa6e9294ff10
Create Date: 2026-08-31 10:12:05.357722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6551336d8f9a'
down_revision = 'fa6e9294ff10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validation_rulesets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dadosgov_organization_id', sa.String(length=64), nullable=False))
        batch_op.alter_column('dadosgov_dataset_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_validation_rulesets_dadosgov_user_id'))
        batch_op.create_index(batch_op.f('ix_validation_rulesets_dadosgov_organization_id'), ['dadosgov_organization_id'], unique=False)
        batch_op.drop_column('dadosgov_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validation_rulesets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dadosgov_user_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_validation_rulesets_dadosgov_organization_id'))
        batch_op.create_index(batch_op.f('ix_validation_rulesets_dadosgov_user_id'), ['dadosgov_user_id'], unique=False)
        batch_op.alter_column('dadosgov_dataset_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.drop_column('dadosgov_organization_id')

    # ### end Alembic commands ###
