"""replace_preprocessing_report_id_with_json_array

Revision ID: 6b015b066d76
Revises: c8037985bcbd
Create Date: 2026-05-18 15:11:34.877538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b015b066d76'
down_revision = 'c8037985bcbd'
branch_labels = None
depends_on = None


def upgrade():
    # Step 1 — add as nullable first so existing rows don't violate the constraint
    with op.batch_alter_table('validation_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preprocessing_report_ids', sa.JSON(), nullable=True))

    # Step 2 — migrate existing data
    op.execute(sa.text("""
        UPDATE validation_reports
        SET preprocessing_report_ids = CASE
            WHEN preprocessing_report_id IS NOT NULL
            THEN json_build_array(preprocessing_report_id)
            ELSE '[]'::json
        END
    """))

    # Step 3 — now safe to enforce NOT NULL and drop the old column
    with op.batch_alter_table('validation_reports', schema=None) as batch_op:
        batch_op.alter_column('preprocessing_report_ids', nullable=False)
        batch_op.drop_index(batch_op.f('ix_validation_reports_preprocessing_report_id'))
        batch_op.drop_constraint(batch_op.f('validation_reports_preprocessing_report_id_fkey'), type_='foreignkey')
        batch_op.drop_column('preprocessing_report_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validation_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preprocessing_report_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('validation_reports_preprocessing_report_id_fkey'), 'preprocessing_reports', ['preprocessing_report_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_validation_reports_preprocessing_report_id'), ['preprocessing_report_id'], unique=False)
        batch_op.drop_column('preprocessing_report_ids')

    # ### end Alembic commands ###
