"""removida a coluna 'passed' de validation_reports

Revision ID: c0013ce1bcec
Revises: 6b015b066d76
Create Date: 2026-06-15 11:12:48.935431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0013ce1bcec'
down_revision = '6b015b066d76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validation_reports', schema=None) as batch_op:
        batch_op.drop_column('passed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validation_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passed', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
