"""status as enum on report models

Revision ID: c8037985bcbd
Revises: e279d9c4871d
Create Date: 2026-05-12 11:22:35.562683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8037985bcbd'
down_revision = 'e279d9c4871d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preprocessing_reports', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('QUEUED', 'STARTED', 'SUCCESS', 'FAILURE', name='taskstatus', native_enum=False),
               existing_nullable=False)

    with op.batch_alter_table('validation_reports', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('QUEUED', 'STARTED', 'SUCCESS', 'FAILURE', name='taskstatus', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validation_reports', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('QUEUED', 'STARTED', 'SUCCESS', 'FAILURE', name='taskstatus', native_enum=False),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)

    with op.batch_alter_table('preprocessing_reports', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('QUEUED', 'STARTED', 'SUCCESS', 'FAILURE', name='taskstatus', native_enum=False),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)

    # ### end Alembic commands ###
