"""initial tables

Revision ID: e279d9c4871d
Revises: 
Create Date: 2026-05-11 13:52:19.036161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e279d9c4871d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preprocessing_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dadosgov_dataset_id', sa.String(length=64), nullable=False),
    sa.Column('dataframe_id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('column_names', sa.JSON(), nullable=True),
    sa.Column('presumed_column_types', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    with op.batch_alter_table('preprocessing_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_preprocessing_reports_dadosgov_dataset_id'), ['dadosgov_dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_preprocessing_reports_dataframe_id'), ['dataframe_id'], unique=False)

    op.create_table('validation_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('preprocessing_report_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rules_applied', sa.JSON(), nullable=True),
    sa.Column('report_result', sa.JSON(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['preprocessing_report_id'], ['preprocessing_reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    with op.batch_alter_table('validation_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_reports_preprocessing_report_id'), ['preprocessing_report_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validation_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_reports_preprocessing_report_id'))

    op.drop_table('validation_reports')
    with op.batch_alter_table('preprocessing_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_preprocessing_reports_dataframe_id'))
        batch_op.drop_index(batch_op.f('ix_preprocessing_reports_dadosgov_dataset_id'))

    op.drop_table('preprocessing_reports')
    # ### end Alembic commands ###
