"""changed structure of the validation_ruleset model as to reflect the possibility of one not being associated with a specific user

Revision ID: fa6e9294ff10
Revises: 7bfa64035c10
Create Date: 2026-08-19 14:32:28.860407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6e9294ff10'
down_revision = '7bfa64035c10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_rulesets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dadosgov_user_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dadosgov_dataset_id', sa.String(length=64), nullable=False),
    sa.Column('dadosgov_resource_id_list', sa.JSON(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('validation_rulesets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_rulesets_dadosgov_dataset_id'), ['dadosgov_dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_rulesets_dadosgov_user_id'), ['dadosgov_user_id'], unique=False)

    with op.batch_alter_table('preprocessing_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dadosgov_resource_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_preprocessing_reports_dadosgov_resource_id'), ['dadosgov_resource_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preprocessing_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_preprocessing_reports_dadosgov_resource_id'))
        batch_op.drop_column('dadosgov_resource_id')

    with op.batch_alter_table('validation_rulesets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_rulesets_dadosgov_user_id'))
        batch_op.drop_index(batch_op.f('ix_validation_rulesets_dadosgov_dataset_id'))

    op.drop_table('validation_rulesets')
    # ### end Alembic commands ###
